### ISSUE TITLE
Website is not being deployed

### ISSUE THREAD

**Issue by JavierCladellas** [feelpp/benchmarking#116]
Fix the workflow so that the website is deployed on push on master. 
The issue most certainly is that the `docs` job depends on `generate_reports`, and does not run on push event. 

Either remove the dependency, or make sure reports are re-generated on push on master.

**Comment by JavierCladellas** [comment]
@prudhomm I have two solutions in mind: 
- Add the condition `if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref_name == 'master')` to the `generate_reports` job. But it can be a bug source for unreviewed reports being deployed.
- Use a workaround for conditional "needs", ensuring docs are always deployed when on master, by adding 
```yml
  docs:
    runs-on: self-ubuntu-22.04
    name: Build Antora Site
    needs: generate_reports
    if: always()
    steps:
         - name: exit if 'docs skip' on commit message
            run: exit 1 ... 
         - name: Deploy:
            if: ${{ github.ref_name == 'master' }}
            ...
```

What do you think?
